import { Party } from "../App";

export const countries: { name: string; parties: Party[] }[] = [
  {
    name: "Germany",
    parties: [
      {
        name: "CDU/CSU",
        shortName: "CDU/CSU",
        seats: 196,
        colour: "#005973",
        position: 50,
        isIndependent: false,
      },
      {
        name: "Sozialdemokratische Partei Deutschlands",
        shortName: "SPD",
        seats: 207,
        colour: "#E3000F",
        position: -50,
        isIndependent: false,
      },
      {
        name: "Alternative für Deutschland",
        shortName: "AfD",
        seats: 77,
        colour: "#00A2DE",
        position: 100,
        isIndependent: false,
      },
      {
        name: "Freie Demokratische Partei",
        shortName: "FDP",
        seats: 91,
        colour: "#FFED00",
        position: 25,
        isIndependent: false,
      },
      {
        name: "Die Linke",
        shortName: "Linke",
        seats: 28,
        colour: "#FF0000",
        position: -75,
        isIndependent: false,
      },
      {
        name: "Bündnis 90/Die Grünen",
        shortName: "Grüne",
        seats: 117,
        colour: "#409A3C",
        position: -25,
        isIndependent: false,
      },
      {
        name: "Bündnis Sahra Wagenknecht",
        shortName: "BSW",
        seats: 10,
        colour: "#792351",
        position: -100,
        isIndependent: false,
      },
      {
        name: "Andere",
        shortName: "",
        seats: 7,
        colour: "#6B7280",
        position: 0,
        isIndependent: true,
      },
    ],
  },
  {
    name: "Belgium",
    parties: [
      {
        name: "Nieuw-Vlaamse Alliantie",
        shortName: "N-VA",
        seats: 24,
        colour: "#FCBD1B",
        position: 75,
        isIndependent: false,
      },
      {
        name: "Vlaams Belang",
        shortName: "VB",
        seats: 20,
        colour: "#FFE500",
        position: 100,
        isIndependent: false,
      },
      {
        name: "Open Vlaamse Liberalen en Democraten",
        shortName: "Open VLD",
        seats: 7,
        colour: "#005daa",
        position: 25,
        isIndependent: false,
      },
      {
        name: "Vooruit",
        shortName: "Vooruit",
        seats: 13,
        colour: "#ff0014",
        position: -50,
        isIndependent: false,
      },
      {
        name: "Groen",
        shortName: "Groen",
        seats: 6,
        colour: "#03ae5c",
        position: -75,
        isIndependent: false,
      },
      {
        name: "Christen-Democratisch en Vlaams",
        shortName: "CD&V",
        seats: 11,
        colour: "#ff8000",
        position: 50,
        isIndependent: false,
      },
      {
        name: "Partij van de Arbeid/Parti du Travail de Belgique",
        shortName: "PVDA-PTB",
        seats: 15,
        colour: "#cc0044",
        position: -75,
        isIndependent: false,
      },
      {
        name: "Mouvement Réformateur",
        shortName: "MR",
        seats: 20,
        colour: "#002eff",
        position: 50,
        isIndependent: false,
      },
      {
        name: "Ecolo",
        shortName: "Ecolo",
        seats: 3,
        colour: "#008d40",
        position: -75,
        isIndependent: false,
      },
      {
        name: "DéFI",
        shortName: "DéFI",
        seats: 1,
        colour: "#dd007a",
        position: 0,
        isIndependent: false,
      },
      {
        name: "Parti Socialiste",
        shortName: "PS",
        seats: 16,
        colour: "#ff0000",
        position: -50,
        isIndependent: false,
      },
      {
        name: "Les Engagés",
        shortName: "LE",
        seats: 14,
        colour: "#00e6d2",
        position: 25,
        isIndependent: false,
      },
    ],
  },
  {
    name: "United Kingdom",
    parties: [
      {
        name: "Labour Party",
        shortName: "Labour",
        seats: 403,
        colour: "#e4003b",
        position: -50,
        isIndependent: false,
      },
      {
        name: "Conservative Party",
        shortName: "Conservative",
        seats: 121,
        colour: "#0087DC",
        position: 50,
        isIndependent: false,
      },
      {
        name: "Liberal Democrats",
        shortName: "Lib Dems",
        seats: 72,
        colour: "#FAA61A",
        position: -25,
        isIndependent: false,
      },
      {
        name: "Scottish National Party",
        shortName: "SNP",
        seats: 9,
        colour: "#FDF38E",
        position: -50,
        isIndependent: false,
      },
      {
        name: "Democratic Unionist Party",
        shortName: "DUP",
        seats: 5,
        colour: "#D46A4C",
        position: 75,
        isIndependent: false,
      },
      {
        name: "Reform UK",
        shortName: "Reform",
        seats: 5,
        colour: "#12B6CF",
        position: 100,
        isIndependent: false,
      },
      {
        name: "Green Party",
        shortName: "Green",
        seats: 4,
        colour: "#02A95B",
        position: -75,
        isIndependent: false,
      },
      {
        name: "Plaid Cymru",
        shortName: "PC",
        seats: 4,
        colour: "#005B54",
        position: -75,
        isIndependent: false,
      },
      {
        name: "Social Democratic and Labour Party",
        shortName: "SDLP",
        seats: 2,
        colour: "#2AA82C",
        position: -50,
        isIndependent: false,
      },
      {
        name: "Alliance Party of Northern Ireland",
        shortName: "APNI",
        seats: 1,
        colour: "#F6CB2F",
        position: 0,
        isIndependent: false,
      },
      {
        name: "Traditional Unionist Voice",
        shortName: "TUV",
        seats: 1,
        colour: "#0C3A6A",
        position: 100,
        isIndependent: false,
      },
      {
        name: "Ulster Unionist Party",
        shortName: "UUP",
        seats: 1,
        colour: "#48A5EE",
        position: 75,
        isIndependent: false,
      },
      {
        name: "Independents",
        shortName: "",
        seats: 9,
        colour: "#6B7280",
        position: 0,
        isIndependent: true,
      },
      {
        name: "Speaker",
        shortName: "Speaker",
        seats: 1,
        colour: "#000000",
        position: 0,
        isIndependent: true,
      },
      {
        name: "Independent Alliance",
        shortName: "IA",
        seats: 5,
        colour: "#555",
        position: -75,
        isIndependent: false,
      },
    ],
  },
  {
    name: "Austria",
    parties: [
      {
        name: "Österreichische Volkspartei",
        shortName: "ÖVP",
        seats: 51,
        colour: "#63C3D0",
        position: 50,
        isIndependent: false,
      },
      {
        name: "Sozialdemokratische Partei Österreichs",
        shortName: "SPÖ",
        seats: 41,
        colour: "#E42712",
        position: -50,
        isIndependent: false,
      },
      {
        name: "Freiheitliche Partei Österreichs",
        shortName: "FPÖ",
        seats: 57,
        colour: "#0056A2",
        position: 100,
        isIndependent: false,
      },
      {
        name: "Die Grünen – Die Grüne Alternative",
        shortName: "Grüne",
        seats: 16,
        colour: "#87B529",
        position: -75,
        isIndependent: false,
      },
      {
        name: "Neos – Das Neue Österreich",
        shortName: "NEOS",
        seats: 18,
        colour: "#CB1667",
        position: 25,
        isIndependent: false,
      },
    ],
  },
];
