import {Party} from "./Seats";

export const countries: { name: string; emoji?: string; parties: Party[] }[] = [
    // {
    //   name: "United States (House)",
    //   parties: [
    //     {
    //       name: "Democratic Party",
    //       shortName: "Dem",
    //       seats: 212,
    //       colour: "#3333FF",
    //       position: -50,
    //       isIndependent: false,
    //     },
    //     {
    //       name: "Republican Party",
    //       shortName: "Rep",
    //       seats: 220,
    //       colour: "#E81B23",
    //       position: 50,
    //       isIndependent: false,
    //     },
    //     {
    //       name: "Vacant",
    //       shortName: "Vacant",
    //       seats: 3,
    //       colour: "#6B7280",
    //       position: 0,
    //       isIndependent: true,
    //     },
    //   ],
    // },
    // {
    //   name: "United States (Senate)",
    //   parties: [
    //     {
    //       name: "Democratic Party",
    //       shortName: "Dem",
    //       seats: 47,
    //       colour: "#3333FF",
    //       position: -50,
    //       isIndependent: false,
    //     },
    //     {
    //       name: "Republican Party",
    //       shortName: "Rep",
    //       seats: 49,
    //       colour: "#E81B23",
    //       position: 50,
    //       isIndependent: false,
    //     },
    //     {
    //       name: "Independent",
    //       shortName: "Ind (Dem)",
    //       seats: 4,
    //       colour: "#6B7280",
    //       position: -25,
    //       isIndependent: true,
    //     },
    //   ],
    //   // regions:
    //   //   [
    //   //     { name: "Alabama", shortName: "AL", seats: 9, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Alaska", shortName: "AK", seats: 3, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Arizona", shortName: "AZ", seats: 11, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Arkansas", shortName: "AR", seats: 6, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "California", shortName: "CA", seats: 54, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Colorado", shortName: "CO", seats: 10, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Connecticut", shortName: "CT", seats: 7, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Delaware", shortName: "DE", seats: 3, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "District of Columbia", shortName: "DC", seats: 3, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Florida", shortName: "FL", seats: 30, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Georgia", shortName: "GA", seats: 16, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Hawaii", shortName: "HI", seats: 4, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Idaho", shortName: "ID", seats: 4, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Illinois", shortName: "IL", seats: 19, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Indiana", shortName: "IN", seats: 11, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Iowa", shortName: "IA", seats: 6, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Kansas", shortName: "KS", seats: 6, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Kentucky", shortName: "KY", seats: 8, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Louisiana", shortName: "LA", seats: 8, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Maine (statewide)", shortName: "ME", seats: 2, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Maine (1st District)", shortName: "ME-1", seats: 1, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Maine (2nd District)", shortName: "ME-2", seats: 1, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Maryland", shortName: "MD", seats: 10, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Massachusetts", shortName: "MA", seats: 11, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Michigan", shortName: "MI", seats: 15, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Minnesota", shortName: "MN", seats: 10, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Mississippi", shortName: "MS", seats: 6, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Missouri", shortName: "MO", seats: 10, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Montana", shortName: "MT", seats: 4, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Nebraska (statewide)", shortName: "NE", seats: 2, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Nebraska (1st District)", shortName: "NE-1", seats: 1, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Nebraska (2nd District)", shortName: "NE-2", seats: 1, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Nebraska (3rd District)", shortName: "NE-3", seats: 1, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Nevada", shortName: "NV", seats: 6, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "New Hampshire", shortName: "NH", seats: 4, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "New Jersey", shortName: "NJ", seats: 14, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "New Mexico", shortName: "NM", seats: 5, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "New York", shortName: "NY", seats: 28, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "North Carolina", shortName: "NC", seats: 16, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "North Dakota", shortName: "ND", seats: 3, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Ohio", shortName: "OH", seats: 17, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Oklahoma", shortName: "OK", seats: 7, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Oregon", shortName: "OR", seats: 8, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Pennsylvania", shortName: "PA", seats: 19, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Rhode Island", shortName: "RI", seats: 4, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "South Carolina", shortName: "SC", seats: 9, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "South Dakota", shortName: "SD", seats: 3, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Tennessee", shortName: "TN", seats: 11, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Texas", shortName: "TX", seats: 40, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Utah", shortName: "UT", seats: 6, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Vermont", shortName: "VT", seats: 3, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Virginia", shortName: "VA", seats: 13, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Washington", shortName: "WA", seats: 12, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "West Virginia", shortName: "WV", seats: 4, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Wisconsin", shortName: "WI", seats: 10, colour: "#6B7280", position: 0, isIndependent: false },
    //   //     { name: "Wyoming", shortName: "WY", seats: 3, colour: "#6B7280", position: 0, isIndependent: false },
    //   // ]
    // },
    {
        name: "European Union",
        emoji: "🇪🇺",
        parties: [
            {
                name: "European People's Party",
                shortName: "EPP",
                seats: 188,
                colour: "#3399FF",
                position: 50,
                isIndependent: false,
            },
            {
                name: "Progressive Alliance of Socialists and Democrats",
                shortName: "S&D",
                seats: 136,
                colour: "#F0001C",
                position: -50,
                isIndependent: false,
            }, {
                name: "Renew Europe",
                shortName: "RE",
                seats: 75,
                colour: "#FFD700",
                position: 0,
                isIndependent: false,
            }, {
                name: "Patriots for Europe",
                shortName: "PfE",
                seats: 86,
                colour: "#2F1C59",
                position: 100,
                isIndependent: false,
            }, {
                name: "European Conservatives and Reformists",
                shortName: "ECR",
                seats: 80,
                colour: "#196CA8",
                position: 75,
                isIndependent: false,

            }, {
                name: "The Greens/European Free Alliance",
                shortName: "Greens",
                seats: 53,
                colour: "#57B45F",
                position: -25,
                isIndependent: false,
            }, {
                name: "The Left in the European Parliament",
                shortName: "Left",
                seats: 46,
                colour: "#B71C1C",
                position: -75,
                isIndependent: false,
            }, {
                name: "Europe of Sovereign Nations",
                shortName: "ESN",
                seats: 26,
                colour: "#13517E",
                position: 100,
                isIndependent: false,
            }, {
                name: "Others",
                shortName: "Others",
                seats: 29,
                colour: "#6B7280",
                position: 0,
                isIndependent: true,
            }, {
                name: "Vacant",
                shortName: "Vacant",
                seats: 1,
                colour: "#6B7280",
                position: 0,
                isIndependent: true,
            }
        ]
    },
    {
        name: "Netherlands",
        emoji: "🇳🇱",
        parties: [
            {
                name: "Partij voor de Vrijheid",
                shortName: "PVV",
                seats: 37,
                colour: "#012758",
                position: 100,
                isIndependent: false,
            }, // Far-right
            {
                name: "Volkspartij voor Vrijheid en Democratie",
                shortName: "VVD",
                seats: 24,
                colour: "#0A2CCA",
                position: 50,
                isIndependent: false,
            }, // Centre-right
            {
                name: "GroenLinks/Partij van de Arbeid",
                shortName: "GL/PvdA",
                seats: 25,
                colour: "#DC1F26",
                position: -50,
                isIndependent: false,
            }, // Centre-left
            {
                name: "Nieuw Sociaal Contract",
                shortName: "NSC",
                seats: 20,
                colour: "#F0C400",
                position: 25,
                isIndependent: false,
            }, // Lean right
            {
                name: "Democraten 66",
                shortName: "D66",
                seats: 9,
                colour: "#00AE41",
                position: -25,
                isIndependent: false,
            }, // Lean left
            {
                name: "Christen-Democratisch Appèl",
                shortName: "CDA",
                seats: 5,
                colour: "#2CC84D",
                position: 25,
                isIndependent: false,
            }, // Centre
            {
                name: "BoerBurgerBeweging",
                shortName: "BBB",
                seats: 7,
                colour: "#94C11F",
                position: 50,
                isIndependent: false,
            }, // Lean right
            {
                name: "Volt",
                shortName: "Volt",
                seats: 2,
                colour: "#582c83",
                position: -25,
                isIndependent: false,
            }, // Lean left
            {
                name: "Partij voor de Dieren",
                shortName: "PvdD",
                seats: 3,
                colour: "#006B2D",
                position: -75,
                isIndependent: false,
            }, // Centre-left
            {
                name: "ChristenUnie",
                shortName: "CU",
                seats: 3,
                colour: "#00A7EE",
                position: 25,
                isIndependent: false,
            }, // Centre
            {
                name: "Staatkundig Gereformeerde Partij",
                shortName: "SGP",
                seats: 3,
                colour: "#EA5B0B",
                position: 75,
                isIndependent: false,
            }, // Right-wing
            {
                name: "Forum voor Democratie",
                shortName: "FvD",
                seats: 3,
                colour: "#841818",
                position: 100,
                isIndependent: false,
            }, // Right-wing
            {
                name: "Socialistische Partij",
                shortName: "SP",
                seats: 5,
                colour: "#F60000",
                position: -75,
                isIndependent: false,
            }, // Left-wing
            {
                name: "Denk",
                shortName: "Denk",
                seats: 3,
                colour: "#00B7B2",
                position: -50,
                isIndependent: false,
            }, // Lean left
            {
                name: "JA21",
                shortName: "JA21",
                seats: 1,
                colour: "#242B57",
                position: 75,
                isIndependent: false,
            }, // Centre-right
        ],
    },
    {
        name: "Germany",
        emoji: "🇩🇪",
        parties: [
            {
                name: "CDU/CSU",
                shortName: "CDU/CSU",
                seats: 208,
                colour: "#005973",
                position: 50,
                isIndependent: false,
            },
            {
                name: "Sozialdemokratische Partei Deutschlands",
                shortName: "SPD",
                seats: 120,
                colour: "#E3000F",
                position: -50,
                isIndependent: false,
            },
            {
                name: "Alternative für Deutschland",
                shortName: "AfD",
                seats: 152,
                colour: "#00A2DE",
                position: 100,
                isIndependent: false,
            },
         //   {
          //      name: "Freie Demokratische Partei",
           //     shortName: "FDP",
           //     seats: 91,
           //     colour: "#FFED00",
           //     position: 25,
           //     isIndependent: false,
         //   },
            {
                name: "Die Linke",
                shortName: "Linke",
                seats: 64,
                colour: "#FF0000",
                position: -75,
                isIndependent: false,
            },
            {
                name: "Bündnis 90/Die Grünen",
                shortName: "Grüne",
                seats: 85,
                colour: "#409A3C",
                position: -25,
                isIndependent: false,
            },
      //      {
      //          name: "Bündnis Sahra Wagenknecht",
      //          shortName: "BSW",
      //          seats: 10,
      //          colour: "#792351",
      //          position: -100,
      //          isIndependent: false,
      //      },
            {
                name: "Südschleswigscher Wählerverband",
                shortName: "SSW",
                seats: 1,
                colour: "#00277E",
                position: 0,
                isIndependent: false,
            },
        ],
    },
    {
        name: "Belgium",
        emoji: "🇧🇪",
        parties: [
            {
                name: "Nieuw-Vlaamse Alliantie",
                shortName: "N-VA",
                seats: 24,
                colour: "#FCBD1B",
                position: 75,
                isIndependent: false,
            },
            {
                name: "Vlaams Belang",
                shortName: "VB",
                seats: 20,
                colour: "#FFE500",
                position: 100,
                isIndependent: false,
            },
            {
                name: "Open Vlaamse Liberalen en Democraten",
                shortName: "Open VLD",
                seats: 7,
                colour: "#005daa",
                position: 25,
                isIndependent: false,
            },
            {
                name: "Vooruit",
                shortName: "Vooruit",
                seats: 13,
                colour: "#ff0014",
                position: -50,
                isIndependent: false,
            },
            {
                name: "Groen",
                shortName: "Groen",
                seats: 6,
                colour: "#03ae5c",
                position: -50,
                isIndependent: false,
            },
            {
                name: "Christen-Democratisch en Vlaams",
                shortName: "CD&V",
                seats: 11,
                colour: "#ff8000",
                position: 50,
                isIndependent: false,
            },
            {
                name: "Partij van de Arbeid/Parti du Travail de Belgique",
                shortName: "PVDA-PTB",
                seats: 15,
                colour: "#cc0044",
                position: -75,
                isIndependent: false,
            },
            {
                name: "Mouvement Réformateur",
                shortName: "MR",
                seats: 20,
                colour: "#002eff",
                position: 50,
                isIndependent: false,
            },
            {
                name: "Ecolo",
                shortName: "Ecolo",
                seats: 3,
                colour: "#008d40",
                position: -50,
                isIndependent: false,
            },
            {
                name: "DéFI",
                shortName: "DéFI",
                seats: 1,
                colour: "#dd007a",
                position: 25,
                isIndependent: false,
            },
            {
                name: "Parti Socialiste",
                shortName: "PS",
                seats: 16,
                colour: "#ff0000",
                position: -50,
                isIndependent: false,
            },
            {
                name: "Les Engagés",
                shortName: "LE",
                seats: 14,
                colour: "#00e6d2",
                position: 25,
                isIndependent: false,
            },
        ],
    },
    {
        name: "United Kingdom",
        emoji: "🇬🇧",
        parties: [
            {
                name: "Labour Party",
                shortName: "Labour",
                seats: 403,
                colour: "#e4003b",
                position: -50,
                isIndependent: false,
            },
            {
                name: "Conservative Party",
                shortName: "Conservative",
                seats: 121,
                colour: "#0087DC",
                position: 50,
                isIndependent: false,
            },
            {
                name: "Liberal Democrats",
                shortName: "Lib Dems",
                seats: 72,
                colour: "#FAA61A",
                position: -25,
                isIndependent: false,
            },
            {
                name: "Scottish National Party",
                shortName: "SNP",
                seats: 9,
                colour: "#FDF38E",
                position: -50,
                isIndependent: false,
            },
            {
                name: "Democratic Unionist Party",
                shortName: "DUP",
                seats: 5,
                colour: "#D46A4C",
                position: 75,
                isIndependent: false,
            },
            {
                name: "Reform UK",
                shortName: "Reform",
                seats: 5,
                colour: "#12B6CF",
                position: 100,
                isIndependent: false,
            },
            {
                name: "Green Party",
                shortName: "Green",
                seats: 4,
                colour: "#02A95B",
                position: -75,
                isIndependent: false,
            },
            {
                name: "Plaid Cymru",
                shortName: "PC",
                seats: 4,
                colour: "#005B54",
                position: -75,
                isIndependent: false,
            },
            {
                name: "Social Democratic and Labour Party",
                shortName: "SDLP",
                seats: 2,
                colour: "#2AA82C",
                position: -50,
                isIndependent: false,
            },
            {
                name: "Alliance Party of Northern Ireland",
                shortName: "APNI",
                seats: 1,
                colour: "#F6CB2F",
                position: 0,
                isIndependent: false,
            },
            {
                name: "Traditional Unionist Voice",
                shortName: "TUV",
                seats: 1,
                colour: "#0C3A6A",
                position: 100,
                isIndependent: false,
            },
            {
                name: "Ulster Unionist Party",
                shortName: "UUP",
                seats: 1,
                colour: "#48A5EE",
                position: 75,
                isIndependent: false,
            },
            {
                name: "Independents",
                shortName: "",
                seats: 9,
                colour: "#6B7280",
                position: 0,
                isIndependent: true,
            },
            {
                name: "Speaker",
                shortName: "Speaker",
                seats: 1,
                colour: "#000000",
                position: 0,
                isIndependent: true,
            },
            {
                name: "Independent Alliance",
                shortName: "IA",
                seats: 5,
                colour: "#555",
                position: -75,
                isIndependent: false,
            },
        ],
    },
    {
        name: "Austria",
        emoji: "🇦🇹",
        parties: [
            {
                name: "Österreichische Volkspartei",
                shortName: "ÖVP",
                seats: 51,
                colour: "#63C3D0",
                position: 50,
                isIndependent: false,
            },
            {
                name: "Sozialdemokratische Partei Österreichs",
                shortName: "SPÖ",
                seats: 41,
                colour: "#E42712",
                position: -50,
                isIndependent: false,
            },
            {
                name: "Freiheitliche Partei Österreichs",
                shortName: "FPÖ",
                seats: 57,
                colour: "#0056A2",
                position: 100,
                isIndependent: false,
            },
            {
                name: "Die Grünen – Die Grüne Alternative",
                shortName: "Grüne",
                seats: 16,
                colour: "#87B529",
                position: -75,
                isIndependent: false,
            },
            {
                name: "Neos – Das Neue Österreich",
                shortName: "NEOS",
                seats: 18,
                colour: "#CB1667",
                position: 25,
                isIndependent: false,
            },
        ],
    },
    {
        name: "Australia (House)",
        emoji: "🇦🇺",
        parties: [
            {
                name: "Liberal Party of Australia",
                shortName: "Liberal",
                seats: 28,
                colour: "#0072B1",
                position: 50,
                isIndependent: false,
            },
            {
                name: "Australian Labor Party",
                shortName: "Labor",
                seats: 94,
                colour: "#E70000",
                position: -50,
                isIndependent: false,
            },
            {
                name: "The Nationals",
                shortName: "Nationals",
                seats: 15,
                colour: "#008000",
                position: 50,
                isIndependent: false,
            },
            {
                name: "Greens",
                shortName: "Greens",
                seats: 1,
                colour: "#4CAF50",
                position: -75,
                isIndependent: false,
            },
            {
                name: "Centre Alliance",
                shortName: "CA",
                seats: 1,
                colour: "#FF6600",
                position: 0,
                isIndependent: false,
            },
            {
                name: "Katter's Australian Party",
                shortName: "KAP",
                seats: 1,
                colour: "#B50204",
                position: 75,
                isIndependent: false,
            },
            {
                name: "Independents",
                shortName: "IND",
                seats: 10,
                colour: "#6B7280",
                position: 0,
                isIndependent: true,
            }
        ],
    },
    {
        name: "Australia (Senate)",
        emoji: "🇦🇺",
        parties: [
            {
                name: "Australian Democrats",
                shortName: "AD",
                seats: 1,
                colour: "#FF6600",
                position: 0,
                isIndependent: false,
            },
            {
                name: "One Nation",
                shortName: "ON",
                seats: 1,
                colour: "#FFD700",
                position: 0,
                isIndependent: false,
            },
        ],
    },
    {
        name: "Canada",
        emoji: "🇨🇦",
        parties: [
            {
                name: "Liberal Party of Canada",
                shortName: "LPC",
                seats: 159,
                colour: "#D71920",
                position: -50,
                isIndependent: false,
            },
            {
                name: "Conservative Party of Canada",
                shortName: "CPC",
                seats: 119,
                colour: "#003366",
                position: 50,
                isIndependent: false,
            },
            {
                name: "Bloc Québécois",
                shortName: "BQ",
                seats: 32,
                colour: "#F58220",
                position: -75,
                isIndependent: false,
            },
            {
                name: "New Democratic Party",
                shortName: "NDP",
                seats: 25,
                colour: "#F37021",
                position: -25,
                isIndependent: false,
            },
            {
                name: "Green Party of Canada",
                shortName: "GPC",
                seats: 3,
                colour: "#64A12D",
                position: -50,
                isIndependent: false,
            }
        ]
    },
    {
        name: "New Zealand",
        emoji: "🇳🇿",
        parties: [
            {
                name: "Labour Party",
                shortName: "Labour",
                seats: 34,
                colour: "#E41B17",
                position: -50,
                isIndependent: false,
            },
            {
                name: "National Party",
                shortName: "National",
                seats: 49,
                colour: "#00529F",
                position: 50,
                isIndependent: false,
            },
            {
                name: "Green Party of Aotearoa New Zealand",
                shortName: "Greens",
                seats: 15,
                colour: "#78BE20",
                position: -75,
                isIndependent: false,
            },
            {
                name: "ACT New Zealand",
                shortName: "ACT",
                seats: 11,
                colour: "#FDE401",
                position: 75,
                isIndependent: false,
            },
            {
                name: "Māori Party",
                shortName: "Māori",
                seats: 6,
                colour: "#B2001A",
                position: -25,
                isIndependent: false,
            },
            {
                name: "New Zealand First",
                shortName: "NZ First",
                seats: 8,
                colour: "#000000",
                position: 8,
                isIndependent: false,
            }
        ]
    }
    // {
    //   name: "Finland",
    //   parties: [
    //     {
    //       "name": "National Coalition Party",
    //       "shortName": "NCP",
    //       "seats": 48,
    //       "colour": "#003580",
    //       "position": 75,
    //       "isIndependent": false
    //     },
    //     {
    //       "name": "Finns Party",
    //       "shortName": "FP",
    //       "seats": 46,
    //       "colour": "#FFD700",
    //       "position": 100,
    //       "isIndependent": false
    //     },
    //     {
    //       "name": "Social Democratic Party",
    //       "shortName": "SDP",
    //       "seats": 43,
    //       "colour": "#E11931",
    //       "position": 0,
    //       "isIndependent": false
    //     },
    //     {
    //       "name": "Centre Party",
    //       "shortName": "CP",
    //       "seats": 23,
    //       "colour": "#01954B",
    //       "position": 25,
    //       "isIndependent": false
    //     },
    //     {
    //       "name": "Green League",
    //       "shortName": "GL",
    //       "seats": 13,
    //       "colour": "#61BF1A",
    //       "position": -25,
    //       "isIndependent": false
    //     },
    //     {
    //       "name": "Left Alliance",
    //       "shortName": "LA",
    //       "seats": 11,
    //       "colour": "#FF0000",
    //       "position": -75,
    //       "isIndependent": false
    //     },
    //     {
    //       "name": "Swedish People's Party",
    //       "shortName": "SPP",
    //       "seats": 9,
    //       "colour": "#FFDD93",
    //       "position": 50,
    //       "isIndependent": false
    //     },
    //     {
    //       "name": "Christian Democrats",
    //       "shortName": "CD",
    //       "seats": 5,
    //       "colour": "#0033A0",
    //       "position": 50,
    //       "isIndependent": false
    //     },
    //     {
    //       "name": "Movement Now",
    //       "shortName": "MN",
    //       "seats": 1,
    //       "colour": "#FF6600",
    //       "position": 75,
    //       "isIndependent": true
    //     }
    //   ]

    // }
];
